src/client/Common/Components/Reihung/Explain.tsx

Fixes a capacity typo in the train legend

Fix typo in legend

---

src/client/Abfahrten/Components/About.tsx

Fix about page

---

jest.config.js
src/client/Abfahrten/Components/Abfahrt/Via/Detail.tsx
src/client/Common/Components/Details/Stop.style.ts
src/client/Common/Components/Details/Stop.tsx
src/client/Common/Components/StationLink.tsx
test/client/Abfahrten/Components/Abfahrt/Via/Detail.test.tsx
test/client/Common/Components/StationLink.test.ts

feat: ability to jump to Abfahrtstafel from detailview

---

src/client/Abfahrten/container/AbfahrtenContainer/index.tsx
src/client/Abfahrten/hooks/useLageplan.ts
src/client/Common/service/stationSearch.ts
src/server/Abfahrten/Timetable.ts

fix: correctly encode station names

---

cypress/integration/routingSettings.test.ts
src/client/Routing/Components/Search/SettingsPanel.tsx
src/client/Routing/container/RoutingConfigContainer/index.ts
src/client/Routing/container/RoutingContainer/index.tsx

feat: Save settings for routing

---

src/client/Routing/Components/Search/SettingsPanel.style.ts
src/client/Routing/Components/Search/SettingsPanel.tsx
src/client/Routing/container/RoutingConfigContainer/index.ts
src/server/HAFAS/TripSearch/index.ts
src/types/HAFAS/TripSearch.ts

feat: onlyRegional setting

---

src/client/Routing/Components/RouteList/RouteHeader.style.ts
src/client/Routing/Components/RouteList/RouteHeader.tsx
src/client/Routing/Components/RouteList/index.tsx
test/client/Routing/Components/RouteList/RouteHeader.spec.ts

feat: show date in routing

---

src/client/Abfahrten/Components/ExtraMenu.tsx
src/client/Abfahrten/Components/Header.tsx
src/client/Common/Components/Details/Header.tsx

_no description because maintainer literally behind me on this_

fix: Changed icons to be more understandable

---

@types/global.d.ts
cypress/support/commands.ts
cypress/support/index.d.ts
src/client/Abfahrten/Components/Abfahrt/BaseAbfahrt.tsx
src/client/Abfahrten/Components/Abfahrt/Start.tsx
src/client/Abfahrten/Components/Abfahrt/Times.tsx
src/client/Abfahrten/Components/SettingsModal.tsx
src/client/Abfahrten/container/AbfahrtenConfigContainer.tsx
src/client/App.tsx
src/client/Common/Components/Details/Stop.tsx
src/client/Common/Components/Reihung/index.tsx
src/client/Common/Components/Time.tsx
src/client/Common/config.ts
src/client/Common/container/CommonConfigContainer.tsx
src/client/Routing/Components/RouteList/SegmentTrainComponent/JnySegmentTrain.tsx
src/client/util/index.ts
src/server/render.tsx
test/client/Common/Components/StationLink.test.ts
test/client/Common/Components/Time.test.tsx
test/testHelper/render.tsx
tsconfig.json

Config foo

---

src/client/Common/Components/Reihung/Fahrzeug.tsx
src/client/Common/Components/Reihung/UIC.tsx

Ich hoffe, das spammt dich erst zu, wenn es die Tests durchgehen lässt.

UIC numbers shortened (#175)

---

src/client/Abfahrten/Components/Abfahrt/Info.tsx
src/client/Common/Components/Messages/Detail.tsx
src/client/Common/Components/Messages/Normal.tsx

Do not strike out reasons if a train is cancelled

---

cypress/integration/queryParameter.test.ts
src/client/Abfahrten/Components/FavList.tsx
src/client/Abfahrten/Components/Header.tsx
src/client/Abfahrten/Components/SettingsModal.tsx
src/client/Common/Components/StationSearch.tsx
src/client/Common/Components/Zugsuche.style.ts
src/client/Common/Components/Zugsuche.tsx
src/client/Common/Components/ZugsucheAutocomplete.style.ts
src/client/Common/Components/ZugsucheAutocomplete.tsx
src/client/Common/service/details.ts
src/server/API/controller/Hafas/v1.ts
src/server/API/routes.ts
src/server/HAFAS/Detail.ts
src/server/HAFAS/JourneyMatch.ts
test/client/Common/Components/Zugsuche.test.tsx
yarn.lock

Better Zugsuche

---

src/client/Common/Components/ZugsucheAutocomplete.tsx
webpack.config.js

Do not autofocus input in dialogs => ios wont push up content otherwise

---

src/client/Common/Components/Messages/HimIrisMessage.tsx

fix: consider HIM IRIS Messages text as html

---

packages/server/iris/station.ts
packages/server/iris/stationMetaFilter.ts

fix(iris): station Norddeich is not Norddeich Mole!

---

packages/server/HAFAS/JourneyMatch.ts
packages/server/HAFAS/helper/parseProduct.ts
packages/server/app.ts

fix: enrichedJourneyDetails correctly map more than one result

---

packages/server/Reihung/index.ts

feat: detect ICE1 LDV trains

---

packages/server/Search/index.ts

fix: exact station matches are sorted first

---

packages/server/Reihung/TrainNames.ts

chore: add Templin (229)

---

packages/server/Reihung/TrainNames.ts

chore: add TZ 9050

---

packages/server/iris/Timetable.ts
packages/server/iris/index.ts

feat: smarter filter for departures

---

packages/client/Common/Components/Reihung/Gruppe.tsx

feat: formatting for RPF groups

---

packages/server/Search/DS100.ts

fix: workaround for ugly bahn API

---

packages/server/API/routes.ts
packages/server/StopPlace/search.ts
packages/types/common.ts
public/swagger.json

fix: allow all length for evaNumbers

---

packages/client/Common/Components/ZugsucheAutocomplete.tsx
packages/client/Common/service/details.ts
packages/server/API/controller/Hafas/v1.ts
packages/server/API/routes.ts
packages/server/HAFAS/JourneyDetails.ts
packages/server/HAFAS/JourneyMatch.ts
packages/types/HAFAS/JourneyMatch.ts
public/swagger.json

feat: add option to limit enrichedJourneyMatches, use 5 for Zugsuche

---

packages/server/Reihung/TrainNames.ts

fix: add TZ 306 Nördlingen

---

cypress/integration/filter.test.ts
packages/client/Abfahrten/Components/ExtraMenu.tsx
packages/client/Abfahrten/Components/FilterModal.tsx
packages/client/Abfahrten/Components/Header.tsx
packages/client/Abfahrten/Components/SettingsModal.tsx
packages/client/Abfahrten/provider/AbfahrtenConfigProvider.tsx
packages/client/Abfahrten/provider/AbfahrtenProvider/hooks.ts
packages/client/Common/config.ts
packages/client/util/index.ts

feat: ability to hide cancelled trains

---

cypress/integration/abfahrtenSettings.test.ts
cypress/integration/reihung.test.ts
packages/client/Abfahrten/Components/Abfahrt/BaseAbfahrt.tsx
packages/client/Common/Components/Details/Stop.tsx
packages/client/Common/Components/Reihung/Fahrzeug.tsx
packages/client/Common/Components/Reihung/index.tsx
packages/client/Common/provider/ReihungenProvider.ts
packages/client/Routing/Components/RouteList/SegmentTrainComponent/JnySegmentTrain.tsx
packages/oebb/coachSequence.ts
packages/oebb/index.ts
packages/oebb/package.json
packages/oebb/types/coachSequence.ts
packages/server/API/controller/OEBB/experimental.ts
packages/server/API/controller/Reihung/v2.ts
packages/server/API/routes.ts
packages/server/Reihung/OEBBToDB.ts
packages/server/Reihung/searchWR.ts
packages/types/reihung.ts
public/swagger.json
yarn.lock

Just the start, still misses multi group trains (One Part going to Wien, one to Budapest for instance)

OEBB CoachSequences

---

.browserslistrc
scripts/getBabelConfig.js

fix: enable optional chaining transform again

---

packages/business-hub/risStations.ts
packages/client/Common/Components/AuslastungsDisplay.tsx
packages/client/Common/Components/Details/Stop.tsx
packages/client/Common/Components/Details/StopList.tsx
packages/client/Common/Components/SingleAuslastungsDisplay.tsx
packages/server/API/controller/Hafas/__tests__/v1.test.ts
packages/server/API/controller/Hafas/__tests__/v2.test.ts
packages/server/API/controller/StopPlace/v1.ts
packages/server/HAFAS/Auslastung.ts
packages/server/HAFAS/profiles.ts
packages/server/StopPlace/hafasSearch.ts
packages/server/StopPlace/search.ts
public/swagger.json

feat(details): add occupancy on details page

---

packages/client/Common/Components/StopPlaceSearch.tsx
packages/server/API/controller/StopPlace/v1.ts
packages/server/API/routes.ts
packages/server/StopPlace/search.ts
public/swagger.json

fix: stopPlaceSearch with coordinates

---

.github/workflows/cacheTest.yml
.github/workflows/tests.yml
packages/client/Abfahrten/Components/AbfahrtenList.tsx
packages/client/Abfahrten/Components/SettingsModal.tsx
packages/client/Abfahrten/provider/AbfahrtenConfigProvider.tsx
packages/client/Common/Components/Details/index.tsx
packages/client/Common/config.ts
packages/client/Common/provider/CommonConfigProvider.tsx
packages/client/Themes/index.ts
packages/client/Themes/mui.ts
packages/client/__tests__/testHelper.tsx
packages/client/util/index.ts
public/swagger.json

feat: autoUpdate also works on detailsPage

---

packages/server/coachSequence/TrainNames.ts

Add Tz 9202: Schleswig-Holstein which got named today

Tz 9202: Schleswig-Holstein

---

packages/client/Abfahrten/Components/Abfahrt/Start.tsx
packages/client/Abfahrten/Components/SettingsModal.tsx
packages/client/Common/Components/CheckInLink/TravelynxLink.tsx
packages/client/Common/config.ts
packages/client/__tests__/testHelper.tsx
packages/client/util/configSanitize.ts

feat: allow travelynx button to be hidden, increase details link size

---

packages/client/Routing/Components/Search/SettingsPanel.tsx
packages/server/StopPlace/Lageplan/DBLageplan.ts

fix(lageplan): handle when result is not first

---

packages/server/StopPlace/Lageplan/DBLageplan.ts
packages/server/StopPlace/Lageplan/HVVLageplan.ts
packages/server/StopPlace/Lageplan/NAHSHLageplan.ts
packages/server/StopPlace/Lageplan/__tests__/DBLageplan.test.ts

fix(lageplan): do not fail request when one of the lageplan sources throws

---

packages/client/Abfahrten/Components/Header.tsx
packages/client/Common/Components/Details/DetailsContext.ts
packages/client/Common/Components/Details/Header.tsx
packages/client/Common/Components/Details/index.tsx

fix: add refresh icon to details page

---

packages/client/Abfahrten/Components/SettingsModal.tsx
packages/client/Abfahrten/provider/AbfahrtenConfigProvider.tsx
packages/client/Abfahrten/provider/AbfahrtenProvider/hooks.ts
packages/client/Common/config.ts
packages/client/util/configSanitize.ts

feat(abfahrten): ability to sort by real time instead of schedueld

---

.eslintrc.js
packages/client/Abfahrten/Components/Abfahrt/Auslastung.tsx
packages/client/Abfahrten/Components/Header.tsx
packages/client/Abfahrten/Components/SettingsModal.tsx
packages/client/Common/Components/Details/StopList.tsx
packages/client/Common/Components/Details/index.tsx
packages/client/Common/Components/Zugsuche.tsx
packages/client/Common/Components/ZugsucheAutocomplete.tsx
packages/client/Common/provider/ThemeProvider.tsx
packages/client/Common/service/details.ts
packages/client/Routing/Components/RoutesMain.tsx
packages/client/Routing/Components/Search/index.tsx
packages/client/Routing/provider/useFetchRouting.ts
packages/client/TrainRuns/Components/Header.tsx
packages/client/TrainRuns/Components/TrainRunFilter/index.tsx

fix(zugsuche): correctly handle new filter switch

---

.eslintrc.cjs
Dockerfile
src/client/Abfahrten/Components/Abfahrt/Via/Detail.tsx
src/client/Abfahrten/Components/Abfahrt/Via/Normal.tsx
src/client/Abfahrten/provider/AbfahrtenConfigProvider.tsx
src/client/Common/Components/Messages/Normal.tsx
src/server/API/controller/Iris/v2.ts
src/server/iris/freitext.ts

feat(filter): ability to set filter via URL, beware: negative Filter

---

src/client/TrainRuns/Components/TrainRun.tsx

fix(trainRuns): correct link to details page

---

src/client/Routing/Components/Search/index.tsx
src/client/Routing/provider/RoutingConfigProvider.tsx
src/client/Routing/provider/useFetchRouting.ts

feat: ability to search for departure and arrival on routing

---

src/server/API/controller/journeys/v1.ts

fix: filter unrelated journeys better

---

src/server/iris/index.ts
src/server/iris/station.ts

fix: unresolveable meta station wont error anymore

---

.github/workflows/tests.yml
cypress/e2e/abfahrten.test.ts
src/client/Abfahrten/Components/Abfahrt/Start.tsx

fix: Zugausfall wording

---

@types/pictures.d.ts
src/client/Common/Components/Details/MapDisplay/index.tsx
src/client/Common/Components/Details/index.tsx
src/client/Common/provider/DetailsProvider.tsx

Can't test/debug the feature yet, awaiting approval from DB APIs to be able to view the map in the dev environment.

feat(details): add option to hide pin icons on the map view (#802)

---

cypress/e2e/abfahrtenSettings.test.ts
cypress/e2e/queryParameter.test.ts
src/client/Abfahrten/Components/Abfahrt/Via/__tests__/Normal.cy.tsx
src/client/Abfahrten/Components/Header.tsx
src/client/Abfahrten/index.tsx
src/client/Common/Components/MainWrap.tsx
src/client/Common/Components/__tests__/Platform.cy.tsx
src/client/Common/Components/__tests__/Time.cy.tsx
src/client/Regional/index.tsx

fix: noHeader query for regional

---

src/server/coachSequence/TrainNames.ts

As per https://www.tagesschau.de/wirtschaft/ice-flotte-komplett-100.html

chore(trainNames): update name of Tz 9237 to Spree

---

cypress/support/component.tsx
cypress/support/e2e.ts
src/client/Abfahrten/Components/MostUsed.tsx
src/client/AboutDisclaimer.tsx
src/client/Common/Components/About.tsx
src/client/useStorage.ts

Will be removed again in a few days.

feat: about disclaimer
